### ISSUE TITLE
Uwa Aloo: Some issues

### ISSUE THREAD

**Issue by Zikt** [ORC-1/ibolang#4]
![image](https://user-images.githubusercontent.com/20236732/55199922-e180be80-51cc-11e9-85ea-520cfe8423da.png)

**Comment by vcnwosu** [comment]
From the look of it, it seems you might not be using ASCII double quotes. It looks like Unicode smart quotes. Do you know if you're keyboard settings is English International or English US? What interface/program did you use to write your `uwaAloo.ibl` file, and can you confirm that you can use neutral style quotation marks with it?

As a quick test, try single quotes and share the result.

**Comment by Zikt** [comment]
I wrote it with Notepad. My keyboard is English US...I'll try single quotation marks

**Comment by Zikt** [comment]
My hello world in Igbo. Issue resolved. This is interesting...
![image](https://user-images.githubusercontent.com/20236732/55212865-794ccf80-5202-11e9-87d5-0072d3c1a606.png)

**Comment by Zikt** [comment]
@Vcnwosu I am excited about this...

**Comment by Zikt** [comment]
This finally!
![image](https://user-images.githubusercontent.com/20236732/55212987-f7a97180-5202-11e9-99f9-962f2520c74d.png)

**Comment by vcnwosu** [comment]
@Zikt I am glad it worked out for you. For future reference, I'd recommend downloading VSCode. It would be more suitable for programming than Notepad. It is also built by Microsoft, so installation should be easy. After which, you should be able to try with double quotes and it should work.
